version: "3.8"

services:
  db:
    container_name: db-server
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "Lem0nCode!"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"
    ports:
      - "1433:1433"
    volumes:
      - type: bind
        source: ./sql-data
        target: /var/opt/mssql/data
volumes:
  sql-data: